name: test-ivy-cron-gpu
on:
  workflow_dispatch:
  schedule:
    - cron: '25 * * * *'
permissions:
  actions: read
jobs:
  run-gpu-tests:
    runs-on: self-hosted
    steps:
      - name: Clean Repository
        run:
          sudo rm -fr $GITHUB_WORKSPACE && mkdir $GITHUB_WORKSPACE

      - name: Checkout Ivy 🛎
        uses: actions/checkout@v2
        with:
          path: ivy
          persist-credentials: false
          submodules: "recursive"
          set-safe-directory: false

      - name: Install ivy and fetch binaries
        run: |
          cd ivy
          pip3 install -e .
          mkdir .ivy
          touch .ivy/key.pem
          echo -n ${{ secrets.USER_API_KEY }} > .ivy/key.pem
          cd ..

      - name: Get Job URL
        uses: Tiryoh/gha-jobid-action@v0
        id: jobs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          job_name: ${{ github.job }}

      - name: Run Tests
        id: tests
        run: |
          pip3 install pymongo
          cd ivy
          python3 scripts/setup_tests/cron_tests.py ${{ github.run_number }}
          python3 scripts/run_tests/run_tests.py ${{ secrets.REDIS_CONNECTION_URL }} ${{ secrets.REDIS_PASSWORD }} ${{ secrets.MONGODB_PASSWORD }} 'false' 'true' ${{ github.run_id }} 'false' ${{ steps.jobs.outputs.html_url }}
        continue-on-error: true

      - name: Check on failures
        if: steps.tests.outcome != 'success'
        run: exit 1
